PROGRAM TPESPECIAL;
USES
	CRT;
CONST
	MIN = 1;
	MAXFIL = 3;
	MAXCOL = 5;
	MAXPLANOS = 3;
	CERO = 0;
TYPE
	TMAT = ARRAY[MIN..MAXFIL , MIN..MAXCOL , MIN..MAXPLANOS] OF INTEGER;

PROCEDURE CARGARMATRIZ(VAR MAT: TMAT);
{CARGA LA MATRIZ PLANO POR PLANO}
VAR
	I,J,K : INTEGER;
BEGIN
	{EN ESTE PROCEDIMIENTO NO PUDE LOGRAR INGRESAR LA MATRIZ EN FORMA RECTANGULAR ASI QUE HICE QUE SE LA INGRESARA POR PLANO, FILA A FILA SEPARADA POR UN ESPACIO, EJ PLANO 1 FILA 1,2,3 SEPARADAS POR UN ESPACIO LUEGO LIMPIA LA PANTALLA Y PIDE EL SIGUIENTE PLANO}
	WRITELN('CARGAR LA MATRIZ PLANO POR PLANO: ');
	WRITELN;
	FOR K:= MIN TO MAXPLANOS DO BEGIN
		CLRSCR;
		WRITELN('PLANO NRO: ',K);
		WRITELN;
		FOR I:= MIN TO MAXFIL DO BEGIN
			FOR J:= MIN TO MAXCOL DO
				READ(MAT[I,J,K]);
			WRITELN;
		END;
	END;
END;

PROCEDURE MOSTRARMATRIZ(MAT: TMAT);
{MUESTRA LA MATRIZ PLANO POR PLANO, ESPERANDO A QUE EL USUARIO APRETE UNA TECLA PARA MOSTRAR EL SIGUIENTE PLANO}
VAR
	I,J,K: INTEGER;
BEGIN
	FOR K:= MIN TO MAXPLANOS DO BEGIN
		WRITELN('PRESIONAR ENTER PARA MOSTRAR EL PLANO NRO: ',K);
		READLN;
		FOR I:= MIN TO MAXFIL DO BEGIN
			FOR J:= MIN TO MAXCOL DO
				WRITE(MAT[I,J,K],' ');
			WRITELN;
		END;
		WRITELN;
	END;
END;

FUNCTION POSEECEROS(MAT: TMAT): BOOLEAN;
{ESTA FUNCION INDICA SI LA MATRIZ POSEE AUNQUE SEA ALGUN CERO PARA PODER OPERAR, ESTO ES RECORRE HASTA QUE ENCUENTRA UN CERO}
VAR
	I,J,K: INTEGER;
	POSEE: BOOLEAN;
BEGIN
	POSEE:= FALSE;
	I:= MIN;
	J:= MIN;
	K:= MIN;
	WHILE (K <= MAXPLANOS) AND (NOT POSEE) DO BEGIN
			WHILE (I <= MAXFIL) AND (NOT POSEE) DO BEGIN
					WHILE (J <= MAXCOL) AND (NOT POSEE) DO BEGIN
							IF (MAT[I,J,K] = CERO) THEN
								POSEE := TRUE;
							J:= J+1;
					END;
					I:= I+1;
					J:=MIN;
			END;
			K:= K+1;
			I:= MIN;
		END;
	POSEECEROS := POSEE;
END;

FUNCTION CANTIDADDECEROSPORFILA(MAT: TMAT; FILA: INTEGER; PLANO: INTEGER): INTEGER;
{ESTA FUNCION INDICA CUANTOS CEROS HAY POR FILA RECORRIENDO TODA LA FILA}
VAR
	J, CANTIDAD: INTEGER;
BEGIN
	CANTIDAD:= 0;
	FOR J:= MIN TO MAXCOL DO
		IF MAT[FILA,J,PLANO] = CERO THEN
			CANTIDAD:= CANTIDAD + 1;
	CANTIDADDECEROSPORFILA := CANTIDAD;
END;

PROCEDURE ORDENARFILA(VAR MAT: TMAT; FILA: INTEGER; PLANO: INTEGER);
{ESTE PROCEDIMIENTO ORDENA LAS FILAS EN BASE A LOS CEROS QUE POSEE, ESTO ES RECORRE TAL FILA HASTA ENCONTRAR UN CERO Y DESPLAZA TODOS LOS NUMEROS DESDE ESE CERO UNA POSICION A LA DERECHA 'PISANDO' ESE CERO}	
VAR
	J,Q: INTEGER;
BEGIN
	FOR J:= MIN TO MAXCOL DO
		IF  (J > MIN) AND (MAT[FILA,J,PLANO] = CERO) THEN 
			FOR Q:= J DOWNTO (MIN+1) DO
				MAT[FILA,Q,PLANO]:= MAT[FILA,Q-1,PLANO];
END;
			
PROCEDURE UBICARCEROS(VAR MAT: TMAT);
{EN BASE A LA CANTIDAD DE CEROS QUE HAY POR FILA COMPLETA EL PRINCIPIO DE LA FILA CON CEROS}
VAR
	I,J,K,CANTCEROS: INTEGER;
BEGIN
	FOR K:= MIN TO MAXPLANOS DO 
		FOR I:= MIN TO MAXFIL DO BEGIN
			CANTCEROS:= CANTIDADDECEROSPORFILA(MAT,I,K);
			ORDENARFILA(MAT,I,K);
			FOR J:= MIN TO CANTCEROS DO
				MAT[I,J,K]:= CERO;
		END;
END;

FUNCTION CANTIDADDECEROSPORPLANO(MAT: TMAT; PLANO: INTEGER): INTEGER;
{DEVUELVE LA CANTIDAD DE CEROS POR PLANO}
VAR
	I,J,CANTCEROS: INTEGER;
BEGIN
	I:= MIN;
	J:= MIN;
	CANTCEROS:= 0;
	FOR I:= MIN TO MAXFIL DO BEGIN
			WHILE (J <= MAXCOL) AND (MAT[I,J,PLANO] = CERO) DO BEGIN
				CANTCEROS:= CANTCEROS+1;
				J:= J+1;	
			END;
			J:= MIN;
	END;
	CANTIDADDECEROSPORPLANO := CANTCEROS;
END;

PROCEDURE BURBUJEODEPLANOS(VAR MAT: TMAT);
{ORDENA LOS PLANOS DE FORMA ASCENDENTE EN BASE A LA CANTIDAD DE CEROS QUE POSEE CADA UNO DE ELLOS, OSEA EN EL PLANO 1 VA A ESTAR EL PLANO QUE TENGA MENOS CEROS Y EN EL ULTIMO PLANO VA A ESTAR EL QUE TENGA MAS CEROS}
VAR
	I,J,K,FRONTERA,AUX: INTEGER;
BEGIN
	FOR FRONTERA:= MAXPLANOS DOWNTO (MIN+1) DO
		FOR K:= MIN TO (FRONTERA - 1) DO
			IF (CANTIDADDECEROSPORPLANO(MAT,K)) > (CANTIDADDECEROSPORPLANO(MAT,K+1)) THEN
				FOR I:= MIN TO MAXFIL DO
					FOR J:= MIN TO MAXCOL DO BEGIN
						AUX:= MAT[I,J,K];
						MAT[I,J,K]:= MAT[I,J,K+1];
						MAT[I,J,K+1]:= AUX;
					END;
END;

VAR {VARIABLES DEL PROGRAMA PRINCIPAL}

	MENTEROS : TMAT;
	OPCION: INTEGER;

BEGIN {PROGRAMA PRINCIPAL}
		WRITELN('1 - CARGAR MATRIZ');
		WRITELN('2 - ORDENAR FILAS (DEJA TODOS LAS CEROS AL PRINCIPIO DE CADA FILA)');
		WRITELN('3 - ORDENAR MATRIZ POR PLANOS (BURBUJEO)');
		WRITELN('4 - MOSTRAR MATRIZ');
		WRITELN('5 - SALIR');
		WRITE('TECLEE LA OPCION DESEADA Y PULSE ENTER: ');
		READLN(OPCION);
		WHILE (OPCION <> 5) DO BEGIN
			CLRSCR;
			CASE OPCION OF
				
				1 : CARGARMATRIZ(MENTEROS); 
				2 : IF POSEECEROS(MENTEROS) THEN 
						UBICARCEROS(MENTEROS)
					ELSE
						WRITELN('LA MATRIZ QUEDA INVARIANTE YA QUE NO POSEE NINGUN CERO');
				3 :	IF POSEECEROS(MENTEROS) THEN 
						BURBUJEODEPLANOS(MENTEROS)
					ELSE
						WRITELN('LA MATRIZ QUEDA INVARIANTE YA QUE NO POSEE NINGUN CERO');
				4 : MOSTRARMATRIZ(MENTEROS);
				
			END;
			WRITELN('ACCION REALIZADA PRESIONE ENTER PARA CONTINUAR');
			READLN;
			CLRSCR;
			WRITELN('1 - CARGAR MATRIZ');
			WRITELN('2 - ORDENAR FILAS (DEJA TODOS LAS CEROS AL PRINCIPIO DE CADA FILA)');
			WRITELN('3 - ORDENAR MATRIZ POR PLANOS (BURBUJEO)');
			WRITELN('4 - MOSTRAR MATRIZ');
			WRITELN('5 - SALIR');
			WRITE('TECLEE LA OPCION DESEADA Y PULSE ENTER: ');
			READLN(OPCION);
		END;
	CLRSCR;
	WRITELN('GRACIAS POR UTILIZAR ESTE SOFTWARE...');
	WRITE('PRESIONE ENTER PARA SALIR...');
	READLN;

END.